export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const CLEAR_SIGNUP_STATE = "CLEAR_SIGNUP_STATE";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS";
export const TOKEN_REFRESH_FAILURE = "TOKEN_REFRESH_FAILURE";
export const SIGN_OUT = "SIGN_OUT";

export const STREAM_CREATE_SUCCESS = "STREAM_CREATE_SUCCESS";
export const STREAM_CREATE_FAILURE = "STREAM_CREATE_FAILURE";
export const STREAM_CREATE_CLEAR = "STREAM_CREATE_CLEAR";

export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE";
