export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const CLEAR_SIGNUP_STATE = "CLEAR_SIGNUP_STATE";
export const SIGN_UP_LOADING = "SIGN_UP_LOADING";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_IN_LOADING = "SIGN_IN_LOADING";

export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS";
export const TOKEN_REFRESH_FAILURE = "TOKEN_REFRESH_FAILURE";
export const TOKEN_REFRESH_LOADING = "TOKEN_REFRESH_LOADING";

export const SIGN_OUT = "SIGN_OUT";

export const STREAM_CREATE_SUCCESS = "STREAM_CREATE_SUCCESS";
export const STREAM_CREATE_FAILURE = "STREAM_CREATE_FAILURE";
export const STREAM_CREATE_LOADING = "STREAM_CREATE_LOADING";

export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE";
export const FETCH_LIST_LOADING = "FETCH_LIST_LOADING";

export const FETCH_SINGLE_STREAM_SUCCESS = "FETCH_SINGLE_STREAM_SUCCESS";
export const FETCH_SINGLE_STREAM_FAILURE = "FETCH_SINGLE_STREAM_FAILURE";
export const FETCH_SINGLE_STREAM_LOADING = "FETCH_SINGLE_STREAM_LOADING";

export const YOUTUBE_SUCCESS = "YOUTUBE_SUCCESS";
export const YOUTUBE_FAILURE = "YOUTUBE_FAILURE";
export const YOUTUBE_LOADING = "YOUTUBE_LOADING";

export const UPDATE_STREAM_SUCCESS = "UPDATE_STREAM_SUCCESS";
export const UPDATE_STREAM_FAILURE = "UPDATE_STREAM_FAILURE";
export const UPDATE_STREAM_LOADING = "UPDATE_STREAM_LOADING";

export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";
export const DELETE_LOADING = "DELETE_LOADING";
